version: '{build}'
skip_tags: true
os: Visual Studio 2015
configuration: 
- Release
- Release-Net45
before_build:
  cmd: nuget restore -DisableParallelProcessing -NonInteractive
build:
  project: Nest.Queryify.sln
  verbosity: minimal
after_build:
  cmd: nuget pack src/Nest.Queryify/Nest.Queryify.csproj -Version %GitVersion_NugetVersion% -IncludeReferencedProjects -Properties "Configuration=%CONFIGURATION%" -Verbosity quiet
artifacts:
- path: Nest.Queryify.*.nupkg
cache: packages -> src\packages.config